const { application } = require('express');
const express = require('express');
const router = express.Router();
const {registerUser, loginUser, getMe, getUserById} = require('../controllers/userController.js');
const {protect} = require('../middleware/authMiddleware.js');
router.post('/', registerUser);
router.post('/login', loginUser);
router.get('/me', protect, getMe);
router.get('/:id', getUserById);
module.exports = router;